const BOARD_ITEM_SIZE = 16;

const BOARD_WIDTH_ITEMS_COUNT = 61;

const BOARD_WIDTH = BOARD_WIDTH_ITEMS_COUNT * BOARD_ITEM_SIZE;

const BOARD_HEIGHT_ITEMS_COUNT = 31;

const BOARD_HEIGHT = BOARD_HEIGHT_ITEMS_COUNT * BOARD_ITEM_SIZE;

const MAX_LEVEL = 7;

const LOCAL_STORAGE_KEY = 'gameState';

const LEVEL_SCORE_CHANGING = 10;

const TICKS_TO_REMOVE_BIG_FOOD = 100;

const POINTS_FOR_BIG_FOOD = 5;

const BIG_FOOD_POINTS = 5;

const INITIAL_MAP = 0;

const INITIAL_LEVEL = 3;

const gameConfig = {
  BIG_FOOD_POINTS,
  BOARD_ITEM_SIZE,
  BOARD_WIDTH_ITEMS_COUNT,
  BOARD_WIDTH,
  BOARD_HEIGHT_ITEMS_COUNT,
  BOARD_HEIGHT,
  INITIAL_LEVEL,
  INITIAL_MAP,
  LEVEL_SCORE_CHANGING,
  LOCAL_STORAGE_KEY,
  MAX_LEVEL,
  POINTS_FOR_BIG_FOOD,
  TICKS_TO_REMOVE_BIG_FOOD,
};

export default gameConfig;
