# docker-compose.yml
version: "3.9"
services:
  postgres:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env.database
    volumes:
      - app-db:/var/lib/postgresql/data

  nginx_brotli:
    image: fholzer/nginx-brotli
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  app:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env.database
    ports:
      - "8080:8080"

volumes:
  app-db:
