# docker-compose.yml
version: "3.9"
services:
  postgres:
    image: postgres:11.2-alpine
    restart: always
    env_file:
      - .env.database
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env.database
    volumes:
      - mongo-data:/data/db

  ssr:
    image: cr.yandex/crp96j9lfkrv2cslsrdh/snake:latest
    volumes:
      - static:/usr/src/app/dist/public:ro
    ports: [ "8080:8080" ]
    nginx:
      image: nginx:1.17-alpine
      restart: unless-stopped
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - static:/usr/share/nginx/html
        - ./data/nginx:/etc/nginx/conf.d
        - ./data/ssl:/etc/letsencrypt
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

volumes:
  postgres-data:
  mongo-data:
  static:
    name: "static"
