# docker-compose.yml
version: "3.9"
services:
  postgres:
    image: postgres:11.2-alpine
    restart: always
    env_file:
      - .env.database
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env.database
    volumes:
      - mongo-data:/data/db

  nginx_brotli:
    image: fholzer/nginx-brotli
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  app:
    build: .
    depends_on:
      - postgres
      - mongo
    env_file:
      - .env.database
    ports:
      - "8080:8080"

volumes:
  postgres-data:
  mongo-data:
