const BOARD_ITEM_SIZE = 16;

const BOARD_WIDTH_ITEMS_COUNT = 62;

const BOARD_WIDTH = BOARD_WIDTH_ITEMS_COUNT * BOARD_ITEM_SIZE;

const BOARD_HEIGHT_ITEMS_COUNT = 31;

const BOARD_HEIGHT = BOARD_HEIGHT_ITEMS_COUNT * BOARD_ITEM_SIZE;

const MAX_LEVEL = 7;

export default {
  BOARD_ITEM_SIZE,
  BOARD_WIDTH_ITEMS_COUNT,
  BOARD_WIDTH,
  BOARD_HEIGHT_ITEMS_COUNT,
  BOARD_HEIGHT,
  MAX_LEVEL,
};
